/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyIdRouteImport } from './routes/survey.$id'
import { Route as AppUpgradeRouteImport } from './routes/_app.upgrade'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppSurveysIndexRouteImport } from './routes/_app.surveys.index'
import { Route as AppRolesIndexRouteImport } from './routes/_app.roles.index'
import { Route as AppResponsesIndexRouteImport } from './routes/_app.responses.index'
import { Route as AppPlansIndexRouteImport } from './routes/_app.plans.index'
import { Route as AppPermissionsIndexRouteImport } from './routes/_app.permissions.index'
import { Route as AppUsersIdRouteImport } from './routes/_app.users.$id'
import { Route as AppSurveysDraftsRouteImport } from './routes/_app.surveys.drafts'
import { Route as AppSurveysCreateRouteImport } from './routes/_app.surveys.create'
import { Route as AppSurveysArchivedRouteImport } from './routes/_app.surveys.archived'
import { Route as AppRolesIdRouteImport } from './routes/_app.roles.$id'
import { Route as AppPlansIdRouteImport } from './routes/_app.plans.$id'
import { Route as AppSurveysSurveyIdAnalyticsRouteImport } from './routes/_app.surveys.$surveyId.analytics'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIdRoute = SurveyIdRouteImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIndexRoute = AppSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppResponsesIndexRoute = AppResponsesIndexRouteImport.update({
  id: '/responses/',
  path: '/responses/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsIndexRoute = AppPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysDraftsRoute = AppSurveysDraftsRouteImport.update({
  id: '/surveys/drafts',
  path: '/surveys/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysCreateRoute = AppSurveysCreateRouteImport.update({
  id: '/surveys/create',
  path: '/surveys/create',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysArchivedRoute = AppSurveysArchivedRouteImport.update({
  id: '/surveys/archived',
  path: '/surveys/archived',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIdRoute = AppRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIdRoute = AppPlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysSurveyIdAnalyticsRoute =
  AppSurveysSurveyIdAnalyticsRouteImport.update({
    id: '/surveys/$surveyId/analytics',
    path: '/surveys/$surveyId/analytics',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/upgrade': typeof AppUpgradeRoute
  '/survey/$id': typeof SurveyIdRoute
  '/plans/$id': typeof AppPlansIdRoute
  '/roles/$id': typeof AppRolesIdRoute
  '/surveys/archived': typeof AppSurveysArchivedRoute
  '/surveys/create': typeof AppSurveysCreateRoute
  '/surveys/drafts': typeof AppSurveysDraftsRoute
  '/users/$id': typeof AppUsersIdRoute
  '/permissions/': typeof AppPermissionsIndexRoute
  '/plans/': typeof AppPlansIndexRoute
  '/responses/': typeof AppResponsesIndexRoute
  '/roles/': typeof AppRolesIndexRoute
  '/surveys/': typeof AppSurveysIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/surveys/$surveyId/analytics': typeof AppSurveysSurveyIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/upgrade': typeof AppUpgradeRoute
  '/survey/$id': typeof SurveyIdRoute
  '/plans/$id': typeof AppPlansIdRoute
  '/roles/$id': typeof AppRolesIdRoute
  '/surveys/archived': typeof AppSurveysArchivedRoute
  '/surveys/create': typeof AppSurveysCreateRoute
  '/surveys/drafts': typeof AppSurveysDraftsRoute
  '/users/$id': typeof AppUsersIdRoute
  '/permissions': typeof AppPermissionsIndexRoute
  '/plans': typeof AppPlansIndexRoute
  '/responses': typeof AppResponsesIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/surveys': typeof AppSurveysIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/surveys/$surveyId/analytics': typeof AppSurveysSurveyIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/survey/$id': typeof SurveyIdRoute
  '/_app/plans/$id': typeof AppPlansIdRoute
  '/_app/roles/$id': typeof AppRolesIdRoute
  '/_app/surveys/archived': typeof AppSurveysArchivedRoute
  '/_app/surveys/create': typeof AppSurveysCreateRoute
  '/_app/surveys/drafts': typeof AppSurveysDraftsRoute
  '/_app/users/$id': typeof AppUsersIdRoute
  '/_app/permissions/': typeof AppPermissionsIndexRoute
  '/_app/plans/': typeof AppPlansIndexRoute
  '/_app/responses/': typeof AppResponsesIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/surveys/': typeof AppSurveysIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/surveys/$surveyId/analytics': typeof AppSurveysSurveyIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/analytics'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/upgrade'
    | '/survey/$id'
    | '/plans/$id'
    | '/roles/$id'
    | '/surveys/archived'
    | '/surveys/create'
    | '/surveys/drafts'
    | '/users/$id'
    | '/permissions/'
    | '/plans/'
    | '/responses/'
    | '/roles/'
    | '/surveys/'
    | '/users/'
    | '/surveys/$surveyId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/analytics'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/upgrade'
    | '/survey/$id'
    | '/plans/$id'
    | '/roles/$id'
    | '/surveys/archived'
    | '/surveys/create'
    | '/surveys/drafts'
    | '/users/$id'
    | '/permissions'
    | '/plans'
    | '/responses'
    | '/roles'
    | '/surveys'
    | '/users'
    | '/surveys/$surveyId/analytics'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/_app/analytics'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_app/upgrade'
    | '/survey/$id'
    | '/_app/plans/$id'
    | '/_app/roles/$id'
    | '/_app/surveys/archived'
    | '/_app/surveys/create'
    | '/_app/surveys/drafts'
    | '/_app/users/$id'
    | '/_app/permissions/'
    | '/_app/plans/'
    | '/_app/responses/'
    | '/_app/roles/'
    | '/_app/surveys/'
    | '/_app/users/'
    | '/_app/surveys/$surveyId/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  SurveyIdRoute: typeof SurveyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$id': {
      id: '/survey/$id'
      path: '/survey/$id'
      fullPath: '/survey/$id'
      preLoaderRoute: typeof SurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/': {
      id: '/_app/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof AppSurveysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/responses/': {
      id: '/_app/responses/'
      path: '/responses'
      fullPath: '/responses/'
      preLoaderRoute: typeof AppResponsesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions/': {
      id: '/_app/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AppPermissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id': {
      id: '/_app/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/drafts': {
      id: '/_app/surveys/drafts'
      path: '/surveys/drafts'
      fullPath: '/surveys/drafts'
      preLoaderRoute: typeof AppSurveysDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/create': {
      id: '/_app/surveys/create'
      path: '/surveys/create'
      fullPath: '/surveys/create'
      preLoaderRoute: typeof AppSurveysCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/archived': {
      id: '/_app/surveys/archived'
      path: '/surveys/archived'
      fullPath: '/surveys/archived'
      preLoaderRoute: typeof AppSurveysArchivedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/$id': {
      id: '/_app/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AppRolesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/$id': {
      id: '/_app/plans/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof AppPlansIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/$surveyId/analytics': {
      id: '/_app/surveys/$surveyId/analytics'
      path: '/surveys/$surveyId/analytics'
      fullPath: '/surveys/$surveyId/analytics'
      preLoaderRoute: typeof AppSurveysSurveyIdAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppPlansIdRoute: typeof AppPlansIdRoute
  AppRolesIdRoute: typeof AppRolesIdRoute
  AppSurveysArchivedRoute: typeof AppSurveysArchivedRoute
  AppSurveysCreateRoute: typeof AppSurveysCreateRoute
  AppSurveysDraftsRoute: typeof AppSurveysDraftsRoute
  AppUsersIdRoute: typeof AppUsersIdRoute
  AppPermissionsIndexRoute: typeof AppPermissionsIndexRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppResponsesIndexRoute: typeof AppResponsesIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppSurveysIndexRoute: typeof AppSurveysIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppSurveysSurveyIdAnalyticsRoute: typeof AppSurveysSurveyIdAnalyticsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppPlansIdRoute: AppPlansIdRoute,
  AppRolesIdRoute: AppRolesIdRoute,
  AppSurveysArchivedRoute: AppSurveysArchivedRoute,
  AppSurveysCreateRoute: AppSurveysCreateRoute,
  AppSurveysDraftsRoute: AppSurveysDraftsRoute,
  AppUsersIdRoute: AppUsersIdRoute,
  AppPermissionsIndexRoute: AppPermissionsIndexRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppResponsesIndexRoute: AppResponsesIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppSurveysIndexRoute: AppSurveysIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppSurveysSurveyIdAnalyticsRoute: AppSurveysSurveyIdAnalyticsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  SurveyIdRoute: SurveyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
